### PR TITLE
Adding .Net Standard support

### PR DESCRIPTION
**Pull request by CodeMyst**
This PR references #54

### CODE REVIEW

**Comment by marshallward** [comment]
I can't really follow most of the metadata changes (`.csproj` etc) but happy to accept them if it helps with .NET standard compliance.

Only one small question was raised above, but should not be taken as a serious issue.  Very happy to accept this.

**Comment by CodeMyst** [comment]
Well for .Net Standard to work it has to use the new `.csproj` file format. Which is also more readable than the old one.

Maybe this article can explain some of the changes: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

**Comment by marshallward** [comment]
Thanks for that, all good.  If you could also include a quick explanation for the change to the constructor in `Map.cs`, and I'll merge this in.

**Comment by CodeMyst** [comment]
.Net Standard doesn't have an overload for `XDocument.Load` that takes in a Stream, so I had to create an `XMLReader` to pass into `XDocument.Load`.

**Comment by marshallward** [comment]
Thanks, makes sense!

**Pull request merged**
