### PR TITLE
Replace DotNetZip with Zlib.Portable

### PR DESCRIPTION
**Pull request by KevinBalz**
Removed zlib source files and added Zlib.Portable Nuget.

### CODE REVIEW

**Comment by marshallward** [comment]
Thanks for this.
I will need to give it a try before I can move ahead, so it might be a bit
slow.

I must admit that I am a bit worried about adding a new dependency, which
might just add to the difficulty of using it. But maybe I am worrying too
much; getting something like MonoGame built is far more difficult!

As for using NuGet - I have added support but don't actually use it much
myself. Does this need to be included in the `TiledSharp.nuspec` file?

**Comment by marshallward** [comment]
Also, I haven't looked into the state of gzip/zlib compatibility with the standard .NET libraries. Maybe this is an option, which eliminates the entire dependency issue?

**Comment by KevinBalz** [comment]
You're right, you must add dependencies to the nuspec, haven't thought about that. src: https://docs.nuget.org/create/creating-and-publishing-a-package (example .nuspec) .  
I'm no nuget expert either, so i will look for a way if it works.  
And System.IO.Compression would be sufficient if Tiled would only support gzip compression, zlib compression seems to be different, but i can't tell how and why as im no compression expert also.

**Comment by marshallward** [comment]
I have read that zlib and gzip libraries can often be used together, since zlib is capable of writing gzip headers, and gzip is capable of understanding the DEFLATE algorithm. But there have also been reports of bloated zlib files under .NET, and unfortunately I never really learned much about the issue.

Anyway, it is probably best to keep using a zlib-dedicated library.

BTW the [Zlib.Portable README](https://github.com/advancedrei/Zlib.Portable/blob/master/README.md) says that its work is being sent to the official DotNetZip repository. Do you know if there's any advantage to using one vs the other?

(Also, I am glad to see that DotNetZip is still being maintained!)

**Comment by marshallward** [comment]
Just heard back from Robert McLaws (that was fast!), he suggested going with the DotNetZip version.
Can you give that one a try and see if it still works with PCLs?

**Comment by KevinBalz** [comment]
I have problems findng the DotNetZip version ( there are a lot of packages named Zlib.Portable). To which one are you referreing to?

**Comment by marshallward** [comment]
Yeah... I see what you mean now.

Zlib.Portable's README points to the 2011 release, which is I was already
using and therefore does not support PCLs.

The DotNetZip version of NuGet does not have any record of patches or
contributions from AdvancedREI, which means this is not where they are
sending their patches (unless they are just sending raw patches via email).

And the NuGet version of DotNetZip does not appear to be any more
"official" anyway, but rather an effort to keep the project alive by new
people.

I will contact Andrew McLaws again, and find out to which repo they has
been sending their patches.

----

Very sorry for making this more complicated than it probably needs to be.
It's only that if I do add an external dependency, then I want to make sure
it's the right one to add!

**Comment by marshallward** [comment]
The new version does not require an external zlib library, so I'll probably close this issue if there are no problems.

**Comment by marshallward** [comment]
Closing this, since an external zlib library is no longer necessary.  Issues with the zlib changes can be handled in separate issues.

**Pull request closed without merging**
